export const categories = [
  { item: 'About',
    icon: 'person',
    information: [],
  },
  { item: 'Experience',
    icon: 'work',
    information:[
      {
        company: 'Tubi',
        title: 'Tech Ops Engineer',
        experiences: [],
      },
      {
        company: 'McMillan Electric',
        title: 'Project Engineer',
        experiences: [
          'Contributed to the acquisition of the electrical contract for Facebook worth $9 million.',
          'Acquired the electrical contract for LEK Consulting worth $450,000.',
          'Maintained excellent relationships with general contractors and subcontractors for prospective business',
          'Managed projects in a high traffic environment and determined budget outcomes by calculating the cost of necessary manpower and material before delivering reports',
          'Surveyed locations of prospective contracts and proposed a bid with an estimated cost for the projects',
        ],
      }
    ],
  },
  { item: 'Skills',
    icon: 'build',
    information: [],
  },
  { item: 'Projects',
    icon: 'web',
    information: [],
  },
  { item: 'Education',
    icon: 'school',
    information: [],
  },
  { item: 'Contact',
    icon: 'mail_outline',
    information: [],
  },
  { item: 'Resume',
    icon: 'list_alt',
    information: [],
  }
];
