export const categories = [
  { item: 'About',
    icon: 'person',
  },
  { item: 'Experience',
    icon: 'work',
  },
  { item: 'Skills',
    icon: 'build',
  },
  { item: 'Projects',
    icon: 'web',
  },
  { item: 'Education',
    icon: 'school',
  },
  { item: 'Contact',
    icon: 'mail_outline',
  },
  { item: 'Resume',
    icon: 'list_alt',
  }
];